### ISSUE TITLE
Bonemeal used on tree sapling logs incorrectly

### ISSUE THREAD

**Issue by rockclimber2009** [Karanum/AdamantineShield#14]
If you place a tree sapling down and then use bonemeal on the sapling and click it with the inspector it'll log the bonemeal as a block break/place.

**Comment by Karanum** [comment]
Verification is needed to see whether this holds true for the newest SpongeAPI version

**Comment by SslaCyhadals** [comment]
This behavior is now intended. The next release will also log all blocks created by growing trees.
