### ISSUE TITLE
Mysql issue

### ISSUE THREAD

**Issue by aWitch-Doctor** [Karanum/AdamantineShield#19]
I feel like an idiot, I can't figure this out. I have the production server and a test server. Production is on a linux box with mysql on the same box. Test server is on my local windows computer with mysql on the same computer. I have the same info for both mysql db's, same databases, same users (permissions should be the same as well), and same login info. On the test server I can get adamantineshield to connect to the db just fine. I copy everything to the production server (which needs all the same info in the config) and it wont work. All plugins and configs are the same. The only differences between production and test are production is set to offline in server.properties and it is setup on waterfall proxy. Test is just a stand alone server with online mode set to true. 

This is the error I keep getting.  https://gist.github.com/aWitch-Doctor/06e2ed0973246eb3058327bb0b85c07d

No tables were being made in the production mysql so i exported all the as_ tables from test mysql to production mysql, it didn't help. I asked another guy with more access in the production db to check the perms for the login info for plugins and he told me that the account has everything except "grant". That couldn't be the cause right? I don't know much about mysql so I don't have a clue what to do now... Is it the plugin or me?

**Comment by aWitch-Doctor** [comment]
So was talking to a person and they suggested that it might be the versions of the mysql db. Production is  5.6.33-0ubuntu0.14.04.1 and test is 5.7.17-log. Could this be the cause? can anyone test this for me? I don't have the ability to update production unless I know it is the cause and I don't have a way to test the production version.

**Comment by Karanum** [comment]
From that error it seems as though Sponge has some issues getting its own SQL service up and running. Sadly I don't know much about Bungee-style setups, or how Sponge manages its SQL service internally, so I can't really offer any help. Your best bet would be to seek help on the Sponge forums/Discord.

**Comment by bakr0008** [comment]
the issue was that the OpenJDK we were running has missing lib and that is JNA lib it is fixed now. 
please close
