### ISSUE TITLE
Cannot get SQL to work

### ISSUE THREAD

**Issue by Julio2546** [Karanum/AdamantineShield#20]
For some reason it keeps saying connection timed out. I'm a noob when it comes to mysql, so any help would be appreciated.

`17.11 13:12:55 [Server] Server thread/ERROR [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=adamantineshield, name=AdamantineShield, version=0.3.3, description=Action logging and rollback plugin for Sponge, authors=[Karanum, Snootiful], source=/./plugins/AdamantineShield-0.3.3.jar}
17.11 13:12:55 [Server] INFO com.google.common.util.concurrent.UncheckedExecutionException: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect to address=(host=db2.voodooservers.com)(port=3306)(type=master) : Connection timed out (Connection timed out)
17.11 13:12:55 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[minecraft_server.1.10.2.jar:?]
17.11 13:12:55 [Server] INFO at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[minecraft_server.1.10.2.jar:?]
17.11 13:12:55 [Server] INFO at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[minecraft_server.1.10.2.jar:?]
17.11 13:12:55 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[minecraft_server.1.10.2.jar:?]
17.11 13:12:55 [Server] INFO at org.spongepowered.common.service.sql.SqlServiceImpl.getDataSource(SqlServiceImpl.java:156) ~[SqlServiceImpl.class:1.10.2-2477-5.2.0-BETA-2698]
17.11 13:12:55 [Server] INFO at org.spongepowered.common.service.sql.SqlServiceImpl.getDataSource(SqlServiceImpl.java:139) ~[SqlServiceImpl.class:1.10.2-2477-5.2.0-BETA-2698]
17.11 13:12:55 [Server] INFO at com.karanumcoding.adamantineshield.db.Database.<init>(Database.java:38) ~[Database.class:?]
17.11 13:12:55 [Server] INFO at com.karanumcoding.adamantineshield.AdamantineShield.onPreInit(AdamantineShield.java:68) ~[AdamantineShield.class:?]
17.11 13:12:55 [Server] INFO at org.spongepowered.common.event.listener.GamePreInitializationEventListener_AdamantineShield_onPreInit1.handle(Unknown Source) ~[?:?]`

I've gone over the config so many times, but I can't see what my error is. It has to be a problem on my end, as it says it could not connect.

`database {
	local-mode = false
	type = "mysql"
	hostname = "db2.voodooservers.com"
	port = 3306
	database = "user2448"
	user = ""
	pass = ""
}`
(I've taken out the user and pass from the above sample)

**Comment by aWitch-Doctor** [comment]
Have you looked at this? https://github.com/Karanum/AdamantineShield/issues/19

I had the same issue, it turned out the version of java we were running on the box was the issue.

**Comment by Julio2546** [comment]
Its since been solved, sorry for not updating.
The database was refusing my servers ip, that’s all lol.
