### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Mikirae** [Karanum/AdamantineShield#26]
Buncha console spam here, not really sure what it means https://pastebin.com/QEZAJDzQ . Only noticed it after updating to .4.0

**Comment by Mikirae** [comment]
I believe it's when you right click a chest.

**Comment by Mikirae** [comment]
Sorry about that. I'm on version 2990, as that is the current recommended version. I can upgrade though, if that will fix the issue.

**Comment by Karanum** [comment]
This issue shouldn't appear on SF 2990 so we'll take a look at what could be causing this.

**Comment by Mikirae** [comment]
Okay, thank you! :)

**Comment by ProsperCraft** [comment]
Same problem, I dropped Prism in favor of this for this reason :)

https://gist.github.com/ProsperCraft/4da037ab8e682185722d721934618c97

[20:59:37] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-a312749
    SpongeForge: 1.12.2-2655-7.1.0-BETA-3025
    Minecraft Forge: 14.23.3.2655
