### ISSUE TITLE
4.1 - Console trace - Could not pass ClickInventoryEvent$Shift$Primary$Impl to Plugin{id=adamantineshield

### ISSUE THREAD

**Issue by ProsperCraft** [Karanum/AdamantineShield#28]
https://gist.github.com/ProsperCraft/2dbffe5f8278c2d5a394bfc533e1e8ba

Using 
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-a312749
    SpongeForge: 1.12.2-2655-7.1.0-BETA-3025
    Minecraft Forge: 14.23.3.2655

Is this related to the plugin not tracking removing items from modded containers like Applied Energistics?

**Comment by Karanum** [comment]
Seems like one of the Sponge classes is acting strange. Do you have more information on when/how this error happens? (Also, there's no need to run the nohoppers version when you run SF 3025)

**Comment by ProsperCraft** [comment]
Its on a large multiplayer server, I don't know how to reproduce it.

Here is another one - 

https://gist.github.com/ProsperCraft/b9008f98a4beef3422ffdd7a245e4912

**Comment by Karanum** [comment]
It's an issue with SpongeCommon that was fixed in SF 3049. You can either use the nohopper version with the recommended SF or upgrade to the latest stable SF.
