### ISSUE TITLE
Could not pass ChangeInventoryEvent

### ISSUE THREAD

**Issue by ziceptor** [Karanum/AdamantineShield#31]
https://gist.github.com/ziceptor/9ab7de4b5680a86f3881df49d0609c34

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-3008.jar
AdamantineShield-0.4.1.jar

**Comment by ziceptor** [comment]
Any news on the hotfix

**Comment by Karanum** [comment]
Looks like this is a bug with SpongeCommon that was fixed in SF 3049. You can either use the nohopper version for the recommended SF, or use the latest stable SF.

**Comment by ziceptor** [comment]
thx
