### ISSUE TITLE
Double chest logging 

### ISSUE THREAD

**Issue by ArKbArKfAcE5** [Karanum/AdamantineShield#7]
Double Chest logging doesn't seem to work, but regular chests and dispensers log fine. Is this a known bug?

**Comment by Karanum** [comment]
I was aware of some logging issues regarding chests. I'll take a look at it ASAP. Thanks for your report.

**Comment by rockclimber2009** [comment]
Any updates on this issue? I have also noticed that indeed double chest transactions are not being logged, but single chest transactions are being logged perfectly fine.
