### ISSUE TITLE
Connections are not closing properly

### ISSUE THREAD

**Issue by Karanum** [Karanum/AdamantineShield#8]
https://gist.github.com/anonymous/f2499527e94114f6503caeb619e684bd

**Comment by Smackzter** [comment]
Update on this issue? Our server just choked out from it.

**Comment by Karanum** [comment]
Haven't really had time to work on AS, though knowing that people still intend to use this plugin makes me want to MAKE time for it now.

Expect a database update within the next few days that will fix this issue, as well as reduce database size some more.

**Comment by Karanum** [comment]
Fixed as of v0.3.0
