### ISSUE TITLE
Chat logging

### ISSUE THREAD

**Issue by rockclimber2009** [Karanum/AdamantineShield#9]
Maybe think of possibly adding a way to log chat and set it as its own permission node. I can think of many times where this would have been very handy to have.

**Comment by rockclimber2009** [comment]
I'm not sure as to how complex the coding would need to be for it, but just a thought.

**Comment by yepidoodles** [comment]
Chat is already logged; do you mean what people said where they were stood? Seems a little pointless to me.

**Comment by Karanum** [comment]
AS will implement chat, command and login/logout logging once most of the main features are done.

It's true that these are already logged in the server logs, but sometimes you just want a quick way of sorting through all that. It should have a negligible impact on performance, though it will increase the size of the database a lot faster so these options will probably be disabled by default once they get added.

**Comment by rockclimber2009** [comment]
No, I meant that through ashield itself you should be able to get chat logs, Because if someone without SSh access isn't around the logs are difficult to get.

**Comment by rockclimber2009** [comment]
Will the command and chat logs be in seperate config options, as logging commands could dramatically increase the file size?

**Comment by Karanum** [comment]
Yes, they will be separated in the config

**Comment by Karanum** [comment]
Chat/command logging is implemented, chat/command lookups will follow soon
